"""template_system

Revision ID: 133056db21a6
Revises: 642e62051696
Create Date: 2026-06-06 23:40:36.273510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '133056db21a6'
down_revision: Union[str, Sequence[str], None] = '642e62051696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filled_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('template_type', sa.String(length=64), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('data_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('minio_path', sa.String(length=2048), nullable=False),
    sa.Column('pdf_path', sa.String(length=2048), nullable=True),
    sa.Column('template_hash', sa.String(length=64), nullable=False),
    sa.Column('generated_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'template_type', 'version_number')
    )
    op.create_index('idx_filled_documents_activity', 'filled_documents', ['activity_id'], unique=False)
    op.add_column('activity_plans', sa.Column('draft_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('activity_plans', sa.Column('current_filled_document_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'activity_plans', ['activity_id'])
    op.create_foreign_key(None, 'activity_plans', 'filled_documents', ['current_filled_document_id'], ['id'], ondelete='SET NULL')
    op.add_column('documents', sa.Column('filled_document_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'documents', 'filled_documents', ['filled_document_id'], ['id'], ondelete='SET NULL')
    op.add_column('key_materials', sa.Column('material_type', sa.String(length=64), nullable=True))
    op.add_column('key_materials', sa.Column('draft_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('key_materials', sa.Column('current_filled_document_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'key_materials', ['activity_id', 'material_type'])
    op.create_foreign_key(None, 'key_materials', 'filled_documents', ['current_filled_document_id'], ['id'], ondelete='SET NULL')
    op.add_column('security_plans', sa.Column('draft_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('security_plans', sa.Column('current_filled_document_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'security_plans', ['activity_id'])
    op.create_foreign_key(None, 'security_plans', 'filled_documents', ['current_filled_document_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # FK constraints must be dropped by name (PostgreSQL requirement)
    op.drop_constraint('security_plans_current_filled_document_id_fkey', 'security_plans', type_='foreignkey')
    op.drop_constraint('security_plans_activity_id_key', 'security_plans', type_='unique')
    op.drop_column('security_plans', 'current_filled_document_id')
    op.drop_column('security_plans', 'draft_data')
    op.drop_constraint('key_materials_current_filled_document_id_fkey', 'key_materials', type_='foreignkey')
    op.drop_constraint('key_materials_activity_id_material_type_key', 'key_materials', type_='unique')
    op.drop_column('key_materials', 'current_filled_document_id')
    op.drop_column('key_materials', 'draft_data')
    op.drop_column('key_materials', 'material_type')
    op.drop_constraint('documents_filled_document_id_fkey', 'documents', type_='foreignkey')
    op.drop_column('documents', 'filled_document_id')
    op.drop_constraint('activity_plans_current_filled_document_id_fkey', 'activity_plans', type_='foreignkey')
    op.drop_constraint('activity_plans_activity_id_key', 'activity_plans', type_='unique')
    op.drop_column('activity_plans', 'current_filled_document_id')
    op.drop_column('activity_plans', 'draft_data')
    op.drop_index('idx_filled_documents_activity', table_name='filled_documents')
    op.drop_table('filled_documents')
