"""add material_id FK to activity_plans and security_plans

Revision ID: 478e3de6e80f
Revises: d105eb7b1994
Create Date: 2026-06-08 22:20:04.395930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '478e3de6e80f'
down_revision: Union[str, Sequence[str], None] = 'd105eb7b1994'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_plans', sa.Column('material_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'activity_plans', 'key_materials', ['material_id'], ['id'], ondelete='SET NULL')
    op.add_column('security_plans', sa.Column('material_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'security_plans', 'key_materials', ['material_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'security_plans', type_='foreignkey')
    op.drop_column('security_plans', 'material_id')
    op.drop_constraint(None, 'activity_plans', type_='foreignkey')
    op.drop_column('activity_plans', 'material_id')
    # ### end Alembic commands ###
