"""initial_baseline

Revision ID: 642e62051696
Revises: 
Create Date: 2026-06-04 00:30:12.744093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '642e62051696'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_type', sa.String(length=128), nullable=False),
    sa.Column('effective_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_reason', sa.Text(), nullable=True),
    sa.Column('resolve_status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('resource', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archive_reason', sa.String(length=1024), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contact_phone', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.Column('estimated_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=512), nullable=False),
    sa.Column('sponsor', sa.String(length=255), nullable=False),
    sa.Column('sponsor_contact', sa.String(length=128), nullable=True),
    sa.Column('sponsor_phone', sa.String(length=64), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('designer_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['designer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('reference_type', sa.String(length=32), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('role_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('comment', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('activity_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('attachment_url', sa.String(length=2048), nullable=True),
    sa.Column('submit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('designer_id', sa.UUID(), nullable=False),
    sa.Column('is_overdue', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['designer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_rule_targets',
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['activity_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('activity_id', 'rule_id')
    )
    op.create_table('activity_status_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=64), nullable=True),
    sa.Column('to_status', sa.String(length=64), nullable=False),
    sa.Column('operator_id', sa.UUID(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_status_log_operator_time', 'activity_status_log', ['operator_id', 'created_at'], unique=False)
    op.create_table('approval_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('liaison_id', sa.UUID(), nullable=False),
    sa.Column('approval_status', sa.String(length=64), nullable=False),
    sa.Column('attachment_url', sa.String(length=2048), nullable=True),
    sa.Column('approval_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rectification_opinion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['liaison_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=True),
    sa.Column('uploader_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=1024), nullable=False),
    sa.Column('minio_path', sa.String(length=2048), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('minio_path')
    )
    op.create_table('filing_docs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('is_qualified', sa.Boolean(), nullable=False),
    sa.Column('handover_status', sa.String(length=64), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id')
    )
    op.create_table('implementation_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('progress', sa.Text(), nullable=True),
    sa.Column('change_status', sa.String(length=64), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('key_materials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_qualified', sa.Boolean(), nullable=False),
    sa.Column('opinion', sa.Text(), nullable=True),
    sa.Column('upload_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sign_status', sa.String(length=32), server_default='unsigned', nullable=False),
    sa.Column('audit_round', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_key_materials_activity_id'), 'key_materials', ['activity_id'], unique=False)
    op.create_table('security_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('risk_level', sa.String(length=64), nullable=True),
    sa.Column('audit_status', sa.String(length=64), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('sign_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filing_doc_materials',
    sa.Column('filing_doc_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['filing_doc_id'], ['filing_docs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['key_materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('filing_doc_id', 'material_id')
    )
    op.create_table('material_audits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('conclusion', sa.String(length=32), nullable=True),
    sa.Column('opinion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['key_materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_plan_materials',
    sa.Column('security_plan_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['key_materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_plan_id'], ['security_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('security_plan_id', 'material_id')
    )
    # ### end Alembic commands ###

    # ── tables not managed by SQLAlchemy models ──
    op.execute("""
        CREATE TABLE IF NOT EXISTS login_attempts (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            login_id VARCHAR(255) NOT NULL,
            ip_address VARCHAR(64),
            success BOOLEAN NOT NULL DEFAULT FALSE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
    """)
    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_login_attempts_login
        ON login_attempts(login_id, created_at)
    """)

    # ── seed roles & permissions ──
    op.execute("""
        INSERT INTO roles (id, name, description) VALUES
            (gen_random_uuid(), 'Promoter', '宣策部人员'),
            (gen_random_uuid(), 'SecurityOfficer', '安保部人员'),
            (gen_random_uuid(), 'AdminStaff', '行政部人员'),
            (gen_random_uuid(), 'GovLiaison', '政府对接人员'),
            (gen_random_uuid(), 'SuperAdmin', '超级管理员'),
            (gen_random_uuid(), 'AdminManager', '行政部负责人'),
            (gen_random_uuid(), 'SecurityManager', '安保部负责人')
        ON CONFLICT (name) DO NOTHING
    """)
    op.execute("""
        INSERT INTO permissions (id, name, resource, action) VALUES
            (gen_random_uuid(), 'create_activity', 'activities', 'create'),
            (gen_random_uuid(), 'upload_plan', 'activities', 'upload_plan'),
            (gen_random_uuid(), 'view_owned_activity', 'activities', 'view_owned'),
            (gen_random_uuid(), 'submit_plan', 'activities', 'submit_plan'),
            (gen_random_uuid(), 'manage_security', 'activities', 'manage_security'),
            (gen_random_uuid(), 'review_security_plan', 'activities', 'review_security_plan'),
            (gen_random_uuid(), 'upload_security_material', 'documents', 'upload'),
            (gen_random_uuid(), 'audit_material', 'materials', 'audit'),
            (gen_random_uuid(), 'sign_document', 'documents', 'sign'),
            (gen_random_uuid(), 'confirm_approval', 'activities', 'confirm_approval'),
            (gen_random_uuid(), 'reject_approval', 'activities', 'reject_approval'),
            (gen_random_uuid(), 'pack_filing', 'filing', 'pack'),
            (gen_random_uuid(), 'view_dashboard', 'dashboard', 'view'),
            (gen_random_uuid(), 'force_cancel', 'activities', 'force_cancel'),
            (gen_random_uuid(), 'force_postpone', 'activities', 'force_postpone'),
            (gen_random_uuid(), 'export_report', 'dashboard', 'export_report'),
            (gen_random_uuid(), 'upload_approval', 'documents', 'upload_approval'),
            (gen_random_uuid(), 'update_approval_status', 'activities', 'update_approval_status'),
            (gen_random_uuid(), 'manage_users', 'users', 'manage'),
            (gen_random_uuid(), 'administer_users', 'users', 'administer'),
            (gen_random_uuid(), 'upload_document', 'documents', 'upload_document')
        ON CONFLICT (name) DO NOTHING
    """)
    op.execute("""
        INSERT INTO role_permissions (role_id, permission_id)
        SELECT r.id, p.id FROM roles r, permissions p
        WHERE r.name = 'Promoter' AND p.name IN (
            'create_activity', 'upload_plan', 'view_owned_activity', 'submit_plan'
        ) ON CONFLICT DO NOTHING
    """)
    op.execute("""
        INSERT INTO role_permissions (role_id, permission_id)
        SELECT r.id, p.id FROM roles r, permissions p
        WHERE r.name = 'SecurityOfficer' AND p.name IN (
            'view_owned_activity', 'upload_security_material', 'sign_document',
            'pack_filing', 'manage_security'
        ) ON CONFLICT DO NOTHING
    """)
    op.execute("""
        INSERT INTO role_permissions (role_id, permission_id)
        SELECT r.id, p.id FROM roles r, permissions p
        WHERE r.name = 'AdminStaff' AND p.name IN (
            'view_owned_activity', 'view_dashboard', 'force_cancel',
            'force_postpone', 'export_report'
        ) ON CONFLICT DO NOTHING
    """)
    op.execute("""
        INSERT INTO role_permissions (role_id, permission_id)
        SELECT r.id, p.id FROM roles r, permissions p
        WHERE r.name = 'GovLiaison' AND p.name IN (
            'view_owned_activity', 'upload_approval', 'update_approval_status',
            'audit_material'
        ) ON CONFLICT DO NOTHING
    """)
    op.execute("""
        INSERT INTO role_permissions (role_id, permission_id)
        SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
        WHERE r.name = 'SuperAdmin'
        ON CONFLICT DO NOTHING
    """)
    op.execute("""
        INSERT INTO role_permissions (role_id, permission_id)
        SELECT r.id, p.id FROM roles r, permissions p
        WHERE r.name = 'AdminManager' AND p.name IN (
            'manage_users', 'view_owned_activity', 'view_dashboard',
            'force_cancel', 'force_postpone', 'export_report'
        ) ON CONFLICT DO NOTHING
    """)
    op.execute("""
        INSERT INTO role_permissions (role_id, permission_id)
        SELECT r.id, p.id FROM roles r, permissions p
        WHERE r.name = 'SecurityManager' AND p.name IN (
            'view_owned_activity', 'manage_security', 'review_security_plan',
            'confirm_approval', 'reject_approval', 'upload_security_material',
            'pack_filing'
        ) ON CONFLICT DO NOTHING
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('security_plan_materials')
    op.drop_table('material_audits')
    op.drop_table('filing_doc_materials')
    op.drop_table('security_plans')
    op.drop_index(op.f('ix_key_materials_activity_id'), table_name='key_materials')
    op.drop_table('key_materials')
    op.drop_table('implementation_records')
    op.drop_table('filing_docs')
    op.drop_table('documents')
    op.drop_table('approval_records')
    op.drop_index('idx_status_log_operator_time', table_name='activity_status_log')
    op.drop_table('activity_status_log')
    op.drop_table('activity_rule_targets')
    op.drop_table('activity_plans')
    op.drop_table('user_roles')
    op.drop_table('role_requests')
    op.drop_table('role_permissions')
    op.drop_table('refresh_tokens')
    op.drop_table('notifications')
    op.drop_table('activities')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('activity_rules')
    # ### end Alembic commands ###
