"""add SecurityPlan last_reject_reason rejected_at

Revision ID: 699146e1cf67
Revises: 6dd678a72c1d
Create Date: 2026-06-08 01:18:04.494556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '699146e1cf67'
down_revision: Union[str, Sequence[str], None] = '6dd678a72c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('security_plans', sa.Column('last_reject_reason', sa.Text(), nullable=True))
    op.add_column('security_plans', sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('security_plans', 'rejected_at')
    op.drop_column('security_plans', 'last_reject_reason')
    # ### end Alembic commands ###
