"""filing_pack_url

Revision ID: 6b6a265f4566
Revises: 133056db21a6
Create Date: 2026-06-07 00:31:04.371175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b6a265f4566'
down_revision: Union[str, Sequence[str], None] = '133056db21a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filing_docs', sa.Column('pack_url', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filing_docs', 'pack_url')
    # ### end Alembic commands ###
