"""make filled_documents minio_path template_hash nullable

Revision ID: 6dd678a72c1d
Revises: 6b6a265f4566
Create Date: 2026-06-08 00:42:17.073379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dd678a72c1d'
down_revision: Union[str, Sequence[str], None] = '6b6a265f4566'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('filled_documents', 'minio_path',
               existing_type=sa.VARCHAR(length=2048),
               nullable=True)
    op.alter_column('filled_documents', 'template_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('filled_documents', 'template_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('filled_documents', 'minio_path',
               existing_type=sa.VARCHAR(length=2048),
               nullable=False)
    # ### end Alembic commands ###
