"""remove unused ActivityRule and ActivityRuleTarget models

Revision ID: 747c22084cc6
Revises: 478e3de6e80f
Create Date: 2026-06-10 02:11:45.994998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '747c22084cc6'
down_revision: Union[str, Sequence[str], None] = '478e3de6e80f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_rules')
    op.drop_table('activity_rule_targets')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_rule_targets',
    sa.Column('activity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rule_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('activity_rule_targets_activity_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['activity_rules.id'], name=op.f('activity_rule_targets_rule_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('activity_id', 'rule_id', name=op.f('activity_rule_targets_pkey'))
    )
    op.create_table('activity_rules',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rule_type', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('effective_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('effective_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resolve_status', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('activity_rules_pkey'))
    )
    # ### end Alembic commands ###
