"""add SecurityPlan reject_count

Revision ID: d105eb7b1994
Revises: 699146e1cf67
Create Date: 2026-06-08 01:29:33.466372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd105eb7b1994'
down_revision: Union[str, Sequence[str], None] = '699146e1cf67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('security_plans', sa.Column('reject_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('security_plans', 'reject_count')
    # ### end Alembic commands ###
