FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir fastapi uvicorn playwright -i https://pypi.tuna.tsinghua.edu.cn/simple

RUN playwright install chromium --with-deps

COPY main.py .

EXPOSE 3000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "3000"]
